spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: journalApp
      auto-index-creation: true
  main:
    allow-circular-references: true 

server:
  port: 8080
  # servlet: 
  #   context-path: /api ------> this gives a path prefix 
# this yml is same as application.properties
