spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: journalApp
      auto-index-creation: true
  main:
    allow-circular-references: true 

server:
  port: 8081
  servlet: 
    context-path: /prod
# this yml is same as application.properties
